export const TEST_INIT_LIST = 'TEST_INIT_LIST';
export type TEST_INIT_LIST = typeof TEST_INIT_LIST;

export const TODOLIST_TITLE_CHANGE = 'TODOLIST_TITLE_CHANGE';
export type TODOLIST_TITLE_CHANGE = typeof TODOLIST_TITLE_CHANGE;

export const TODOLIST_INIT_LIST = 'TODOLIST_INIT_LIST';
export type TODOLIST_INIT_LIST = typeof TODOLIST_INIT_LIST;
