CREATE TABLE bill (
    `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT ,
    `u_id` INT UNSIGNED NOT NULL COMMENT '创建用户id',
    `category_id` INT UNSIGNED NOT NULL COMMENT '类别id，对应category表',
    `category_type` SMALLINT(1) UNSIGNED NOT NULL COMMENT '收入：0，支出1',
    `price` FLOAT UNSIGNED NOT NULL COMMENT '价格',
    `bill_time` DATE NOT NULL COMMENT '记账时间',
    `remark` VARCHAR(10) COMMENT '备注',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB CHARSET=utf8 COMMENT='明细表';
